version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              libnss3 \
              xvfb \
              libatk1.0-0 \
              libatk-bridge2.0-0 \
              libgtk-3-0 \
              libgbm-dev \
              libnotify-dev \
              libgconf-2-4 \
              libnss3 \
              libxss1 \
              libasound2 \
              libxtst6 \
              xauth \
              xcb \
              libx11-xcb1 \
              libxcomposite1

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Node Modules
          command: npm install

      - run:
          name: Install Cypress
          command: npx cypress install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/Cypress
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
